---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Welcome all!!


Welcome to the introduction to population genetics and data analysis in R programming language workshop. This workshop is designed to provide a very brief overview of concept of population genetics and its data analysis in R. 

## Objectives and motivation


When I was an undergraduate, I did not know a lot about population genetics and had no idea about R programming language. When I first came to US to get my M.S in plant pathology, I saw that most people where attracted towards using free statistical and programming software R. I started teaching R myself. Joining Niklaus Grunwald lab at USDA-ARS for my Ph.D. was a major turning point in learning R. I had an excellent peers to learn from Dr. Zhian Kamvar and Dr. Javier Tabima (developers of R package poppr which will talk a lot) and Dr. Brian Knaus (developer of R package VCFR). Our lab is one of the leading labs to organize population genetics workshop in R here in US and have been involved in development of several otherpackages. 

I knew that Nepalese undergraudates lack knowledge and skills about population genetics and R programming. Therefore I submitted a proposal to American Phytopathological Society to conduct a workshop in Nepal. The proposal was approved and this workshop is also supported through Department of Botany and Plant Pathology at Oregon State University.


We cannot learn population genetics and R programming in just 3 days. Don't be discouraged. My primary goal is to teach you to provide basic concepts and navigate you to right directions. Therefore this site will also contain links to other repositories which has excellent resources on R, data analysis and visualization.   


## Final words

There are many people to thank and the list will keep growing. First, I want to thank my advisor Nik Grunwald, lab members: Zhian Kamvar, Javier Tabima, Brian Knaus, Zach Foster and Nick Carleson for their support. I must thank host country coordinator Subodh Khanal for helping in putting the proposal. This work is funded by American Phytopathological Society (APS) through Global experience fund awarded to Shankar K. Shakya (Ph.D. candidate, Oregon State University) and Subodh Khanal (assistant prof, Tribhuwan University, Nepal). Paklihawa campus, Tribhuwan University is the host institution. 